version: "3"
services: 
  node: 
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo


  mongo:
    container_name: mongo
    image : mvertes/alpine-mongo
    ports:
    - '27017:27017'
